version: '3.8'

services:
  mqtt-presence:
      build: .
      image: mqtt-presence:latest
      container_name: mqtt-presence
      ports:
        - "8100:8100"
      volumes:
        - ./config/:/config
        - ./log/:/log
      #privileged: true