name: Test workflow

on:
  workflow_dispatch:


permissions:
  contents: write  # notwendig für Upload zur GitHub Release


jobs:
  build-test-create-exe:
    name: 🛠️ Create exe
    runs-on: windows-latest

    steps:
      - name: ✨ Checkout repo
        uses: actions/checkout@v4


      - name: ⚖️ Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'


      - name: ↑ Install build tools and deps
        run: python -m pip install --upgrade pip build setuptools wheel pytest pylint toml


      - name: 🕒 Run version update script
        run: python scripts/pre_build.py


      - name: 📥 Install package and dependencies
        run: pip install .


      - name: 📦 Build package
        run: python -m build
        

      - name: 🧠 Analysing the code with pylint
        run: python -m pylint $(git ls-files '*.py')
        

      - name: 🧪 Run tests
        shell: pwsh
        run: |
          if (Test-Path -Path tests -PathType Container) {
            python -m pytest tests
          } else {
            Write-Output "No tests directory found."
          }


      - name: 📦 Install PyInstaller
        run: pip install pyinstaller
        # Bildvorschlag: 🛠️ oder ![installer](https://img.icons8.com/ios-filled/50/download.png)


      - name: 🏗️ Build .exe with PyInstaller
        run: pyinstaller mqtt-presence.spec
        # Bildvorschlag: 🏗️ oder ![exe](https://img.icons8.com/ios-filled/50/windows8.png)


      - name: Rename executable with version
        run: |
          $tag = "${{ github.ref_name }}"
          Rename-Item -Path "dist/mqtt-presence.exe" -NewName "mqtt-presence-$tag.exe"


      #- name: 💾 🐍 📜 📁 Upload .exe to GitHub Release
      #  uses: softprops/action-gh-release@v2
      #  with:
      #    files: dist/mqtt-presence-*.exe          