name: Create Release and Publish to PyPI + Docker

on:
  workflow_dispatch:
  #push:
  #  tags:
  #    - 'v*'

permissions:
  contents: write

env:
  IMAGE_NAME: mqtt-presence

jobs:  
  docker:
    name: 🐳 Build & Push Docker Image
    runs-on: ubuntu-latest
    #needs: release

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🐳 Log in to Docker Hub
        if: secrets.DOCKER_USERNAME != '' && secrets.DOCKER_PASSWORD != ''
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 🔐 Log in to GitHub Container Registry (GHCR)
        if: secrets.CR_PAT != ''
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: 🐳 Build and tag Docker image
        run: |
          docker build -t mqtt-presence:base .
          docker tag mqtt-presence:base ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
          docker tag mqtt-presence:base ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
          docker tag mqtt-presence:base ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
          docker tag mqtt-presence:base ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}

      - name: 📤 Push to Docker Hub
        if: secrets.DOCKER_USERNAME != '' && secrets.DOCKER_PASSWORD != ''
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}

      - name: 📤 Push to GitHub Container Registry
        if: secrets.CR_PAT != ''
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
          docker push ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
