name: Release to TestPyPI

on:
  push:
    tags:
      - 'v*'

    
permissions:
  contents: write  # notwendig für Upload zur GitHub Release

jobs:
  build-and-publish:
    name: Prepare Release
    runs-on: windows-latest


    steps:
      - name: ✨ Checkout repo
        uses: actions/checkout@v4

      - name: ⚖️ Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: ↑ Install build tools and deps
        run: |
          python -m pip install --upgrade pip build setuptools wheel
          pip install pytest pylint toml

      - name: Run version update script
        run: python scripts/pre_build.py

      - name: Build package
        run: python -m build


      - name: Analysing the code with pylint
        run: |
          pip install .
          python -m pylint $(git ls-files '*.py')


      - name: Run tests
        shell: pwsh
        run: |
          if (Test-Path -Path tests -PathType Container) {
            python -m pytest tests
          } else {
            Write-Output "No tests directory found."
          }
          

      - name: Install PyInstaller
        run: |
          pip install pyinstaller              

      - name: Build .exe with PyInstaller
        run: pyinstaller mqtt-presence.spec          
  

      - name: Rename executable with version
        run: |
          $tag = "${{ github.ref_name }}"
          Rename-Item -Path "dist/mqtt-presence.exe" -NewName "mqtt-presence-$tag.exe"        

      - name: Upload .exe to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/mqtt-presence-*.exe


          
  upload-to-PyPi:
    runs-on: ubuntu-latest
    needs: build-and-publish

    steps:
      - name: ✨ Checkout repo
        uses: actions/checkout@v4

      - name: ⚖️ Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: ↑ Install build tools and deps
        run: |
          python -m pip install --upgrade pip build setuptools wheel
          pip install pytest pylint toml

      - name: Run version update script
        run: python scripts/pre_build.py

      - name: Build package
        run: python -m build


      - name: Analysing the code with pylint
        run: |
          pip install .
          pylint $(git ls-files '*.py')


      - name: Run tests
        run: |
          if [ -d tests ]; then
            pytest tests
          else
            echo "No tests directory found."
          fi
          

        
      - name: Upload dist files to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*.whl
            dist/*.tar.gz


      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://upload.pypi.org/legacy/
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}    
              
