name: Release to TestPyPI

on:
  push:
    tags:
      - 'v*'  # Nur Tags die mit v anfangen

permissions:
  contents: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build tools and deps
        run: |
          python -m pip install --upgrade pip build setuptools wheel
          pip install toml

      - name: Run version update script
        run: python scripts/pre_build.py

      - name: Build package
        run: python -m build

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
