name: Build and Test mqtt-presence

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: 🛠️ Build and test on Python ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: ✨ Checkout repo
        uses: actions/checkout@v4


      - name: ⚖️ Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'


      - name: ↑ Install build tools and deps
        run: python -m pip install --upgrade pip build setuptools wheel pytest pylint toml


      - name: 🕒 Run version update script
        run: python scripts/pre_build.py


      - name: 📥 Install package and dependencies
        run: pip install .


      - name: 📦 Build package
        run: python -m build
        

      - name: 🧠 Analysing the code with pylint
        run: python -m pylint $(git ls-files '*.py')

        
      - name: 🧪 Run tests
        run: |
          if [ -d tests ]; then
            pytest tests
          else
            echo "No tests directory found."
          fi
